[project]
name = "chapitre3-labs1-uv"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "p-fievet-ece", email = "paul.fievet@edu.ece.fr" }
]
requires-python = ">=3.13"
dependencies = [
    "faker>=40.40.0",
]

[project.scripts]
dataset-users = "chapitre3_labs1_uv.dataset_users:main"
dataset-orders = "chapitre3_labs1_uv.dataset_orders:main"

[build-system]
requires = ["uv_build>=0.12.10,<0.13.0"]
build-backend = "uv_build"
